---
title: "Project notes"
format: pdf
editor: visual
---

# Political overreach and firm dynamics:

Existing research has documented that there exists private return to holding political office as well as value in being connected to politicians. However, there is limited understanding of the mechanism through which these gains are generated, specially when politicians have very little executive powers.

In this project, I investigate this in Indian setting where political overreach into bureaucracy is a common phenomenon. Using the universe of bureaucratic postings and transfers and biographical data on state level politicians, I empirically document that politician's characteristics are associated with unusual transfer patterns.

These politically motivated transfers and postings are likely to affect the bureaucrats ability to properly function, affecting local state capacity. I test the effects of this variation in state capacity on local firm dynamics, specifically ease of firm entry and firm level investments. Essentially, I am investigating the mechanism that politicians have negative spillover effects when they reduce the local state capacity and firms observe this and respond to the political intervention.

# Monopsony in informal labor markets.

I investigate a unique feature of the informal labor markets in India where due to regulatory costs, most small firms hire workers through a third party subcontractor.

A priori the subcontractors can potentially reduce the hiring search friction, but overtime they also are likely to develop a market power and can potentially reduce labor supply as firms. This is because hiring costs are convex for the subcontractors and its increasingly hard for firms to incentive subcontractors to hire.

I model these costs as a new source of friction along the growth trajectory of firm and estimate the effect of subcontractor labor market power on both firm productivity and wages.

# Impact of police funding inequality on local crime and police performance in US

Police departments in USA draw majority of their funding from revenues generated by local governments. This creates potential for inequality in their funding driven by unequal income dynamics across cities within a MSA.

Fact: There are small cities within metropolitan St. Louis that pay 3 times the police officer salaries of other small cities. The low salary departments are in high-poverty majority-minority communities.

Research question: What are the consequences of this arrangement for the allocation of police officers, the quality of police representation in majority-minority communities, and aggregate crime and officer-involved violence?

Using a shift share instrument, we estimate the effects of increasing income inequality in MSA's with high-levels of fiscal fragmentation (i.e., instances where the population is divided across many different legally and fiscally independent cities), both relative to increasing inequality when fragmentation is low, and relative to highly fragmented MSA's that do not see increasing inequality.

Learnings from this project has crucial policy relevant implications for funding public services across different jurisdictions and improving police performance.

This project is motivated by the fact that political overreach into bureaucracy is quite common in India. Existing research has documented some of its effects in terms of private gains acrued to politicians, but we still do not have proper understanding of the mecanism returns of holding political office or value of being connected to a politician. However, there is limited undertanding about the mechanism through which these returns are generated specially when politicians have virtually no executive power.

I match the universe of beorocratic postings and transfers data with biographical data on elected representatives and document the effects of political overreach on the local state capacity ( using abnormal term limits of the beurocrats). Further, I use this reduction in state capacity to develop quantitative estimates for effects on local firm dynamics.

Political overreach; beurocratic incentive ( transfers); firm entry and investment

The project is motivated by the fact that, in India, politicians routinely encroach into beurocratic decision making to increase their personal benefit. This encroachment has potential to reduce the local state capacity by making Eurocrats less powerful in their own domain if their decisions are routinely overruled through the politician. Using the detailed data on postings and tr4ansfers of government officianls, I document the the effects of this political overreach. Following this, I use this reducedtion in state capacity to develop quantitative effects on local firm dynamics. In the end growth effects.

Labor market power:

Police Funding inequality
