rm(list=ls())
source("code/functions.R")


# NOTES -------------------------------------------------------------------

# 1. "ASI/generated_data/Clean/Final/asi_plant_panel1980-2016_district.dta"
#  has districtname variable that does not have any missing. 
# still might need to take care of district name changes. 
# "nic98_4" seem to have lower missing rate (2%) in this data. 
# and can be used to categorized industries. There are unique 
# 148 levels for NIC 98 4 digit. 
# 2. Now the task would be to construct both the export share 
# in these NIC level as well as global market share, both as a time series
# 3. Then the idea is that given a high enough export share
#.   high global market share firms grow faster (because they have higher surplus due to pricing power). 
#.4. Is this exercise worth doing? what do we get out of it? Is it defensible?

# 5. Is there another experimental version that you can think of?

# 6. Another next task is to get some measures of Y variable (size growth, etc). 


# 0 FUNCTIONS -------------------------------------------------------------

get_sumstat <- function(data, group_vars, 
                        summary_vars) {
  library(dplyr)
  
  # Group by the specified grouping variables and summarize each summary variable
  summary_table <- data %>%
    group_by(across(all_of(group_vars))) %>%
    summarize(
      n = n(),  # Total count for each group to calculate missing percentage
      across(
        all_of(summary_vars), 
        list(
          min = ~min(., na.rm = TRUE),
          max = ~max(., na.rm = TRUE),
          median = ~median(., na.rm = TRUE),
          mean = ~mean(., na.rm = TRUE),
          sd = ~sd(., na.rm = TRUE),
          missing_pct = ~sum(is.na(.)) / n() * 100,  # Missing percentage
          unique_vals = ~n_distinct(.)
        ),
        .names = "{.col}_{.fn}"
      )
    ) %>%
    ungroup() %>%
    select(-n)  # Remove total count column if it's not needed
  
  return(summary_table)
}

# Example usage:
# summary_table <- generate_summary(my_data, group_vars = c("group_var1", "group_var2"), summary_vars = c("var1", "var2"))

# 1 READING ---------------------------------------------------------------



# THis is data from Fiona's ASI github repo, 
# generated by Sunny and Simoni and Subba etc RAs

# a doc with much details is present at
# \miss_docs\ASI_data_cleaning.pdf

dist_panel1=read_dta("/Users/vaibhavrathi/Dropbox/ASI/generated_data/Clean/Final/asi_plant_panel1980-2016_district.dta")

pooled_df=read_dta("/Users/vaibhavrathi/Dropbox/ASI/generated_data/ASI1992-2010_stacked.dta")







# 2 Explore ---------------------------------------------------------------

df=pooled_df %>% sample_frac(0.1)
pp=pooled_df %>% 
  mutate(fd=as.numeric(substr(as.character(nic87), 
                              1, 1))) %>% 
  mutate(nc=nchar(nic87))


