structure(list(field_of_experience = c("Agriculture", "Dairy", 
"Cooperatives", "Area Development", "Animal Husbandry", "Fisheries", 
"Seeds", "Sericulture", "Horticulture", "Poultry", "Agricultural Marketing", 
"Agricultural Research & Education", "Commercial Crops", "Plant Protection", 
"Crops", "Marine Products", "Agriculture & Cooperation", NA, 
"Vigilance", "Fertilizers", "Petro-Chemicals", "Chemicals & Petro-Chemicals", 
"Chemicals & Fertilizers", "Chemicals", "Commerce", "Export Promotion", 
"Foreign Trade", "Tea", "Rubber", "State Trading", "Coffee", 
"Tobacco", "Cashewnut", "Leather", "Coconut", "Spices", "Trade Fairs", 
"Marketing", "Imports Exports", "Licensing Policy", "Communication", 
"Information Technology", "Telecommunication", "Electronic Data Processing", 
"e-Governance", "Communications & Information Technology", "Management Information System", 
"Posts", "Public Distribution", "Civil Supplies", "Consumer Affairs", 
"Food", "Food & Civil Supplies", "Food Storage", "Consumer Affairs, Food & PD", 
NA, "Corporate Management (New)", "Accounting & Finance", "Archaeology", 
"Archives Admn", "Cultural Affairs", "Culture", "Defence", "Defence Production & Supplies", 
"National Security", "Ex-Service Men's Welfare", "Defence Service Welfare", 
"Defence Research", "Defence Policy", NA, "Cantonment Administration", 
"North-East Development", "North East Policy", "Development of NER", 
"Power", "Energy", "Atomic Energy", "Non-Conventional Energy", 
"Power (Corporate Mgmt)", "Electricity", "New & Renewable Energy", 
"Hydro-Electric Power", "Solar Energy", "Forests", "Environment & Pollution Control", 
"Wild Life", "Soil Conservation", "Environment", "Pollution Control", 
"Climate Change", "Ecology", "Environment & Forests", NA, "Forest Protection", 
"Internal Cooperation", "External Relations", "External Affairs", 
"Overseas Indian Affairs", "International Diplomacy", "Passports", 
"Foreigners Visa", "Internal Affairs", "Revenue", "Finance", 
"Economic Affairs", "Institutional Finance", "Excise", "Expenditure", 
"Sales Tax", "Pay Commission", "Registration", "Enforcement", 
"Budget", "Investment", "Disinvestment", "Commercial Taxes", 
"Banking", "Finance Commission", "Monetary Policy", "Income Tax", 
"Financial Planning", "Insurance", "Financial Mgmt", NA, "Health & Family Welfare", 
"Family Welfare", "Medical Institutes", "Disease Control", "Ayurveda", 
"Public Health", "Health Admn.", "Drugs", "Medical Education", 
"Medical Services", "Medicines", "Rural Health", "Political Affairs", 
"Home", "Rehabilitation", "Police", "Internal Security", "Relief", 
"Jails", "Census", "Foreigners' Matters", "Human Rights", "Border Management", 
"National Integration", "Official Language", "Disaster Management", 
"Relief & Rehabilitation", "Coordination", "Law & Order", "J & K Affairs", 
"Personnel Management", "Education", "Higher Education", "Technical Education", 
"Elementry Education", "Languages", "School Education", "Human Resource Dev", 
"Educational Research", "Adult Literacy", "Physical Education", 
"Libraries", NA, "Manpower Planning", "Industrial production", 
"Industries", "Small Scale Industries", "Heavy Industries", "Agro Industries", 
"Handicrafts Dev", "Leather Industry", "Handloom Dev", "Food Processing Industries", 
"Khadi & Village Industries", "Sugar Industry", "Industrial Financing", 
"Industrial Dev", "Industrial Policy & Promotion", "Public Enterprises", 
"Small & Village Industry", "Steel", "Industrial Investment", 
"Industrial Planning", "Rural Industry", "Industrial Training", 
"Industrial Policy", NA, "Industries Dev", "Public Relations", 
"Doordarshan", "Information", "Films", "Printing & Publications", 
"Information & Broadcasting", "Publicity", NA, "Labour", "Labour & Employment", 
"Employment & Training", "Employment", "Labour Welfare", "Bonded Labour", 
"Sub Divisional Admn", "District Admn", "Land Reforms", "Settlement", 
"Development Admn", "Revenue Admn", "Divisional Admn", "Land Revenue", 
"Land Dev", "Land Acquision", "Consolidation", "Land Records", 
"Land Resources", "Land Revenue Mgmt & District Admn", NA, "Land Management", 
"Judicial", "Company Affairs", "Elections", "Legal Affairs", 
"Tribunals", "Appeal", "Law & Justice", "Civil Law", "Justice", 
"Legislative", "Law and Justice", NA, "Panchayati Raj", "Local Self Govt", 
"Mail Management", "Mines", "Coal", "Geology", "Mines & Minerals", 
"Coal (Corporate Mgmt)", "Mines (Corporate Mgmt)", "Mining", 
"Metals", "Alloys", "N.A.", NA, "Not Applicable", "Not Available", 
"N.Applicable", "Parliament", "Legislature", "Parliamentary Affairs", 
"Legislative Affairs", "Personnel Mgmt", "Cabinet Affairs", "General Administration", 
"Public Grievances", "Administrative Reforms", "Personnel and General Administration", 
"Personnel Training", "Pensions", "Vigilance", "Right to Information (RTI)", 
"Enquiries", "Service Commission", "Services", "Recruitment", 
"Personnel Policy", "Pensioners Welfare", NA, "Appointments", 
"IT intervention in HR Management", "Petroleum", "Petroleum & Natural Gas", 
"Natural Gas", "Petroleum (Corporate Mgmt)", "Planning", "Statistics", 
"Programme Implementation", "Plan Coordination", "Policy Planning", 
"Project Mgt.", "Project Formulation", "Economics & Statistics", 
"Evaluation", "Planning & Prog Implementation", NA, "Survey", 
NA, "Liaison", "Public Administration", NA, "Law", NA, "Public Policy", 
"Public Works", "Public Works-Roads", "Public Works-Buildings", 
NA, "Survey , planning and Construction", "Rural Development", 
"Wasteland Dev", "Land Resources", "Drinking Water Supply", "Rural Housing", 
"Rural Employment", "Rural Dev", "Public Health Engg.", "Rural Banking", 
"SC", "Space", "Science & Technology", "Ocean Dev", "Bio-Technology", 
"Scientific & Industrial Research", "Earth Science", "Recruitment Bd", 
"Welfare", "Prohibition", "Minorities Welfare", "Backward Class Welfare", 
"Social Welfare", "Disabled Welfare", "Social Justice & Empowerment", 
"Religious Endowment", "Tribal Welfare", "SC Welfare", "ST Welfare", 
NA, "Ministers Office", "Chief Minister's Sectt.", "Governor's Sectt.", 
"Prime Minister's Office", "President's Secretariat", "Staff Officers", 
NA, "Vice-President's Sectt.", "Handicrafts", "Jute", "Textiles", 
"Handlooms", "Wool", "Coir", "Silk", "Cotton", "Synthetic Textiles", 
"Tourism", "Hotel Management", "Eco-Tourism", NA, "Training", 
"Technology and Legal", "International Cooperation", "Enterprise Leadership Programme", 
"Ports", "Transport", "Shipping", "Civil Aviation", "Road Transport", 
"Civil Aviation (Corporate Mgmt)", "Highways", "Railways", "Water Transport", 
NA, "Road Bridge Infrastructure", "Municipal Administration", 
"Urban Develoment", "Town & Country Planning", "Urban Housing", 
"Development Authority", "Poverty Alleviation", "Land & Building", 
"Urban Planning", "Colonization", "Estates", NA, "Urban Development", 
"Slum Dev", "Public, Urban & Revenue Administration", "Irrigation", 
"Flood Control", "Water Resources", "Drinking Water", "River Control Board", 
"Command Area Dev", "Ground Water", "Watershed Mgmt", "General Admin", 
"Womens Dev", "Child Dev", "Women & Child Dev", NA, "Youth Affairs & Sports", 
"Sports", "Youth Affairs", NA), category_of_experience = c("Agriculture & Cooperation", 
"Agriculture & Cooperation", "Agriculture & Cooperation", "Agriculture & Cooperation", 
"Agriculture & Cooperation", "Agriculture & Cooperation", "Agriculture & Cooperation", 
"Agriculture & Cooperation", "Agriculture & Cooperation", "Agriculture & Cooperation", 
"Agriculture & Cooperation", "Agriculture & Cooperation", "Agriculture & Cooperation", 
"Agriculture & Cooperation", "Agriculture & Cooperation", "Agriculture & Cooperation", 
"Agriculture & Cooperation", "Agriculture & Cooperation", "Anti-Corruption", 
"Chemicals & Fertilizers", "Chemicals & Fertilizers", "Chemicals & Fertilizers", 
"Chemicals & Fertilizers", "Chemicals & Fertilizers", "Commerce", 
"Commerce", "Commerce", "Commerce", "Commerce", "Commerce", "Commerce", 
"Commerce", "Commerce", "Commerce", "Commerce", "Commerce", "Commerce", 
"Commerce", "Commerce", "Commerce", "Communications & Information Technology", 
"Communications & Information Technology", "Communications & Information Technology", 
"Communications & Information Technology", "Communications & Information Technology", 
"Communications & Information Technology", "Communications & Information Technology", 
"Communications & Information Technology", "Consumer Affairs, Food & PD", 
"Consumer Affairs, Food & PD", "Consumer Affairs, Food & PD", 
"Consumer Affairs, Food & PD", "Consumer Affairs, Food & PD", 
"Consumer Affairs, Food & PD", "Consumer Affairs, Food & PD", 
"Consumer Affairs, Food & PD", "Corporate Management (New)", 
"Corporate Management (New)", "Culture", "Culture", "Culture", 
"Culture", "Defence", "Defence", "Defence", "Defence", "Defence", 
"Defence", "Defence", "Defence", "Defence", "Development of NER", 
"Development of NER", "Development of NER", "Energy", "Energy", 
"Energy", "Energy", "Energy", "Energy", "Energy", "Energy", "Energy", 
"Environment & Forests", "Environment & Forests", "Environment & Forests", 
"Environment & Forests", "Environment & Forests", "Environment & Forests", 
"Environment & Forests", "Environment & Forests", "Environment & Forests", 
"Environment & Forests", "Environment & Forests", "External Affairs", 
"External Affairs", "External Affairs", "External Affairs", "External Affairs", 
"External Affairs", "External Affairs", "External Affairs", "Finance", 
"Finance", "Finance", "Finance", "Finance", "Finance", "Finance", 
"Finance", "Finance", "Finance", "Finance", "Finance", "Finance", 
"Finance", "Finance", "Finance", "Finance", "Finance", "Finance", 
"Finance", "Finance", "Finance", "Health & Family Welfare", "Health & Family Welfare", 
"Health & Family Welfare", "Health & Family Welfare", "Health & Family Welfare", 
"Health & Family Welfare", "Health & Family Welfare", "Health & Family Welfare", 
"Health & Family Welfare", "Health & Family Welfare", "Health & Family Welfare", 
"Health & Family Welfare", "Home", "Home", "Home", "Home", "Home", 
"Home", "Home", "Home", "Home", "Home", "Home", "Home", "Home", 
"Home", "Home", "Home", "Home", "Home", "Home", "Human Resource Dev", 
"Human Resource Dev", "Human Resource Dev", "Human Resource Dev", 
"Human Resource Dev", "Human Resource Dev", "Human Resource Dev", 
"Human Resource Dev", "Human Resource Dev", "Human Resource Dev", 
"Human Resource Dev", "Human Resource Dev", "Human Resource Dev", 
"Industrial production", "Industries", "Industries", "Industries", 
"Industries", "Industries", "Industries", "Industries", "Industries", 
"Industries", "Industries", "Industries", "Industries", "Industries", 
"Industries", "Industries", "Industries", "Industries", "Industries", 
"Industries", "Industries", "Industries", "Industries", "Industries", 
"Information & Broadcasting", "Information & Broadcasting", "Information & Broadcasting", 
"Information & Broadcasting", "Information & Broadcasting", "Information & Broadcasting", 
"Information & Broadcasting", "Information & Broadcasting", "Labour & Employment", 
"Labour & Employment", "Labour & Employment", "Labour & Employment", 
"Labour & Employment", "Labour & Employment", "Land Revenue Mgmt & District Admn", 
"Land Revenue Mgmt & District Admn", "Land Revenue Mgmt & District Admn", 
"Land Revenue Mgmt & District Admn", "Land Revenue Mgmt & District Admn", 
"Land Revenue Mgmt & District Admn", "Land Revenue Mgmt & District Admn", 
"Land Revenue Mgmt & District Admn", "Land Revenue Mgmt & District Admn", 
"Land Revenue Mgmt & District Admn", "Land Revenue Mgmt & District Admn", 
"Land Revenue Mgmt & District Admn", "Land Revenue Mgmt & District Admn", 
"Land Revenue Mgmt & District Admn", "Land Revenue Mgmt & District Admn", 
"Land Revenue Mgmt & District Admn", "Law and Justice", "Law and Justice", 
"Law and Justice", "Law and Justice", "Law and Justice", "Law and Justice", 
"Law and Justice", "Law and Justice", "Law and Justice", "Law and Justice", 
"Law and Justice", "Law and Justice", "Local Self Govt", "Local Self Govt", 
"Mail Management", "Mines & Minerals", "Mines & Minerals", "Mines & Minerals", 
"Mines & Minerals", "Mines & Minerals", "Mines & Minerals", "Mines & Minerals", 
"Mines & Minerals", "Mines & Minerals", "N.Applicable", "N.Applicable", 
"N.Applicable", "N.Applicable", "N.Available", "Parliamentary Affairs", 
"Parliamentary Affairs", "Parliamentary Affairs", "Parliamentary Affairs", 
"Personnel and General Administration", "Personnel and General Administration", 
"Personnel and General Administration", "Personnel and General Administration", 
"Personnel and General Administration", "Personnel and General Administration", 
"Personnel and General Administration", "Personnel and General Administration", 
"Personnel and General Administration", "Personnel and General Administration", 
"Personnel and General Administration", "Personnel and General Administration", 
"Personnel and General Administration", "Personnel and General Administration", 
"Personnel and General Administration", "Personnel and General Administration", 
"Personnel and General Administration", "Personnel and General Administration", 
"Personnel and General Administration", "Petroleum & Natural Gas", 
"Petroleum & Natural Gas", "Petroleum & Natural Gas", "Petroleum & Natural Gas", 
"Planning & Prog Implementation", "Planning & Prog Implementation", 
"Planning & Prog Implementation", "Planning & Prog Implementation", 
"Planning & Prog Implementation", "Planning & Prog Implementation", 
"Planning & Prog Implementation", "Planning & Prog Implementation", 
"Planning & Prog Implementation", "Planning & Prog Implementation", 
"Planning & Prog Implementation", "Planning & Prog Implementation", 
"Project Appraisal and Risk Management", "Protocol", "Public Administration", 
"Public Administration", "Public Administration", "Public Policy", 
"Public Policy", "Public Works", "Public Works", "Public Works", 
"Public Works", "Railway Project", "Rural Dev", "Rural Dev", 
"Rural Dev", "Rural Dev", "Rural Dev", "Rural Dev", "Rural Dev", 
"Rural Dev", "Rural Dev", "ST Welfare", "Science & Technology", 
"Science & Technology", "Science & Technology", "Science & Technology", 
"Science & Technology", "Science & Technology", "Service Commn", 
"Social Justice & Empowerment", "Social Justice & Empowerment", 
"Social Justice & Empowerment", "Social Justice & Empowerment", 
"Social Justice & Empowerment", "Social Justice & Empowerment", 
"Social Justice & Empowerment", "Social Justice & Empowerment", 
"Social Justice & Empowerment", "Social Justice & Empowerment", 
"Social Justice & Empowerment", "Social Justice & Empowerment", 
"Staff Officers", "Staff Officers", "Staff Officers", "Staff Officers", 
"Staff Officers", "Staff Officers", "Staff Officers", "Staff Officers", 
"Textiles", "Textiles", "Textiles", "Textiles", "Textiles", "Textiles", 
"Textiles", "Textiles", "Textiles", "Tourism", "Tourism", "Tourism", 
"Tourism", "Training", "Training", "Training", "Training", "Transport", 
"Transport", "Transport", "Transport", "Transport", "Transport", 
"Transport", "Transport", "Transport", "Transport", "Transport", 
"Urban Development", "Urban Development", "Urban Development", 
"Urban Development", "Urban Development", "Urban Development", 
"Urban Development", "Urban Development", "Urban Development", 
"Urban Development", "Urban Development", "Urban Development", 
"Urban Development", "Urban Development", "Water Resources", 
"Water Resources", "Water Resources", "Water Resources", "Water Resources", 
"Water Resources", "Water Resources", "Water Resources", "Water Resources", 
"Women & Child Dev", "Women & Child Dev", "Women & Child Dev", 
"Women & Child Dev", "Youth Affairs & Sports", "Youth Affairs & Sports", 
"Youth Affairs & Sports", NA), line_item = c("", "Dairy Development", 
"Co-operation", "", "Animal Husbandry", "Fisheries", "", "", 
"", "", "", "Agricultural Research and Education", "", "", "", 
"", "", "", "Secretariat - General Services", "Industries", "Industries", 
"Industries", "Industries", "Industries", "Industries", "Industries", 
"Industries", "Village and Small Industries", "Village and Small Industries", 
"Village and Small Industries", "Village and Small Industries", 
"Village and Small Industries", "Village and Small Industries", 
"Village and Small Industries", "Village and Small Industries", 
"Village and Small Industries", "", "", "", "", "Science, Technology and Environment", 
"Science, Technology and Environment", "Science, Technology and Environment", 
"", "", "", "", "", "Housing, Food Storage and Warehousing", 
"Civil Supplies", "", "", "Civil Supplies", "Housing, Food Storage and Warehousing", 
"", "", "", "", "Education, Sports, Art and Culture", "", "Education, Sports, Art and Culture", 
"Education, Sports, Art and Culture", "", "", "", "", "", "", 
"", "", "", "", "", "", "Energy", "Energy", "Energy", "Energy", 
"Energy", "Energy", "Energy", "Energy", "Energy", "Forestry and Wild Life", 
"", "Forestry and Wild Life", "Soil and Water Conservation", 
"Forestry and Wild Life", "", "", "Forestry and Wild Life", "Forestry and Wild Life", 
"", "", "", "", "", "", "", "", "", "", "Secretariat - General Services", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "Family Welfare", "Family Welfare", "Medical and Public Health", 
"Medical and Public Health", "Medical and Public Health", "Medical and Public Health", 
"Medical and Public Health", "Medical and Public Health", "Medical and Public Health", 
"Medical and Public Health", "Medical and Public Health", "Medical and Public Health", 
"Secretariat - General Services", "Secretariat - General Services", 
"", "Police", "", "Relief on account of Natural Calamities", 
"", "", "", "", "", "", "", "Relief on account of Natural Calamities", 
"", "", "", "", "", "Education, Sports, Art and Culture", "Education, Sports, Art and Culture", 
"Education, Sports, Art and Culture", "Education, Sports, Art and Culture", 
"Education, Sports, Art and Culture", "Education, Sports, Art and Culture", 
"Education, Sports, Art and Culture", "Education, Sports, Art and Culture", 
"Education, Sports, Art and Culture", "Education, Sports, Art and Culture", 
"Education, Sports, Art and Culture", "Education, Sports, Art and Culture", 
"", "Industries", "Industries", "Village and Small Industries", 
"Industries", "Industries", "Village and Small Industries", "Village and Small Industries", 
"Village and Small Industries", "Industries", "Village and Small Industries", 
"Industries", "Industries", "Industries", "Industries", "Industries", 
"Village and Small Industries", "Industries", "Industries", "Industries", 
"Village and Small Industries", "Industries", "Industries", "Industries", 
"Industries", "", "", "", "", "", "", "", "", "Labour and Labour Welfare", 
"Labour and Labour Welfare", "Labour and Labour Welfare", "Labour and Labour Welfare", 
"Labour and Labour Welfare", "Labour and Labour Welfare", "District Administration", 
"District Administration", "District Administration", "District Administration", 
"District Administration", "District Administration", "District Administration", 
"District Administration", "District Administration", "District Administration", 
"District Administration", "District Administration", "District Administration", 
"District Administration", "District Administration", "District Administration", 
"", "", "", "", "", "", "", "", "", "", "", "", "Rural Development", 
"Rural Development", "", "", "Non-Ferrous Mining and Metallurgical Industries", 
"Non-Ferrous Mining and Metallurgical Industries", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "Rural Development", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "Welfare of Scheduled Castes, Scheduled Tribes and Other Backward Classes", 
"", "", "", "", "Welfare of Scheduled Castes, Scheduled Tribes and Other Backward Classes", 
"Welfare of Scheduled Castes, Scheduled Tribes and Other Backward Classes", 
"Welfare of Scheduled Castes, Scheduled Tribes and Other Backward Classes", 
"", "", "", "", "", "", "", "", "", "Village and Small Industries", 
"Village and Small Industries", "Industries", "Village and Small Industries", 
"Village and Small Industries", "Village and Small Industries", 
"Village and Small Industries", "Village and Small Industries", 
"Industries", "Tourism", "Tourism", "Tourism", "", "", "", "", 
"", "Others", "Roads and Bridges", "Others", "Others", "Roads and Bridges", 
"", "Roads and Bridges", "", "", "", "Roads and Bridges", "Urban Development", 
"Urban Development", "Urban Development", "Urban Development", 
"Urban Development", "Urban Development", "Urban Development", 
"Urban Development", "Urban Development", "Urban Development", 
"Urban Development", "Urban Development", "Urban Development", 
"Urban Development", "Major and Medium Irrigation", "Major and Medium Irrigation and Flood Control", 
"", "", "", "", "", "Soil and Water Conservation", "", "", "", 
"", "", "", "", "", ""), sector = c("Agriculture and Allied Activities", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "Administrative Services", "Industry and Minerals", "", "", 
"", "", "Industry and Minerals", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "Science, Technology and Environment", 
"", "", "", "", "", "", "", "Agriculture and Allied Activities", 
"General Economic Services", "", "", "", "", "General Economic Services", 
"", "", "", "Social Services", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "Energy", "", "", "", "", "", "", 
"", "", "Agriculture and Allied Activities", "", "", "Agriculture and Allied Activities", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Administrative Services", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "Social Services", "", "", "", "", "", "", 
"", "", "", "", "", "Administrative Services", "", "", "", "", 
"Social Services", "", "", "", "", "", "", "", "Social Services", 
"", "", "", "", "", "Social Services", "", "", "", "", "", "", 
"", "", "", "", "", "", "Industry and Minerals", "Industry and Minerals", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "Social Services", 
"", "", "", "", "", "Administrative Services", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "Rural Development", "Rural Development", 
"", "Industry and Minerals", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "Rural Development", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "Social Services", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "Industry and Minerals", "", "", "", "", "", "", 
"", "", "General Economic Services", "", "", "", "", "", "", 
"", "Transport", "", "", "", "", "", "", "", "", "", "", "Social Services", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "Irrigation and Flood Control", 
"", "", "", "", "", "", "Agriculture and Allied Activities", 
"", "Social Services", "", "", "", "Social Services", "", "", 
""), recheck = c("", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", 
"yes", "yes", "yes", "yes", "yes", "", "yes", "", "", "", "", 
"", "yes", "yes", "yes", "yes", "yes", "yes", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "yes", "", "", "", "yes", 
"yes", "", "", "", "", "", "", "", "", "", "", "", "", "yes", 
"yes", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "yes", "", "", "", "", "", "", "", 
"yes", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "")), row.names = c("1", 
"2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", 
"14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", 
"25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", 
"36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", 
"47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", 
"58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", 
"69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", 
"80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", 
"91", "92", "93", "94", "95", "96", "97", "98", "99", "100", 
"101", "102", "103", "104", "105", "106", "107", "108", "109", 
"110", "111", "112", "113", "114", "115", "116", "117", "118", 
"119", "120", "121", "122", "123", "124", "125", "126", "127", 
"128", "129", "130", "131", "132", "133", "134", "135", "136", 
"137", "138", "139", "140", "141", "142", "143", "144", "145", 
"146", "147", "148", "149", "150", "151", "152", "153", "154", 
"155", "156", "157", "158", "159", "160", "161", "162", "163", 
"164", "165", "166", "167", "168", "169", "170", "171", "172", 
"173", "174", "175", "176", "177", "178", "179", "180", "181", 
"182", "183", "184", "185", "186", "187", "188", "189", "190", 
"191", "192", "193", "194", "195", "196", "197", "198", "199", 
"200", "201", "202", "203", "204", "205", "206", "207", "208", 
"209", "210", "211", "212", "213", "214", "215", "216", "217", 
"218", "219", "220", "221", "222", "223", "224", "225", "226", 
"227", "228", "229", "230", "231", "232", "233", "234", "235", 
"236", "237", "238", "239", "240", "241", "242", "243", "244", 
"245", "246", "247", "248", "249", "250", "251", "252", "253", 
"254", "255", "256", "257", "258", "259", "260", "261", "262", 
"263", "264", "265", "266", "267", "268", "269", "270", "271", 
"272", "273", "274", "275", "276", "277", "278", "279", "280", 
"281", "282", "283", "284", "285", "286", "287", "288", "289", 
"290", "291", "292", "293", "294", "295", "296", "297", "298", 
"299", "300", "301", "302", "303", "304", "305", "306", "307", 
"308", "309", "310", "311", "312", "313", "314", "315", "316", 
"317", "318", "319", "320", "321", "322", "323", "324", "325", 
"326", "327", "328", "329", "330", "331", "332", "333", "334", 
"335", "336", "337", "338", "339", "340", "341", "342", "343", 
"344", "345", "346", "347", "348", "349", "350", "351", "352", 
"353", "354", "355", "356", "357", "358", "359", "360", "361", 
"362", "363", "364", "365", "366", "367", "368", "369", "370", 
"371", "372", "373", "374", "375", "376", "377", "378", "379", 
"380", "381", "382", "383", "384", "385", "386", "387", "388", 
"389", "390", "391", "392", "393", "394", "395", "396", "397", 
"398"), class = "data.frame")
